[project]
name = "lab-async-weather-news-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioconsole>=0.8.1",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
]
